name: Rust CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust environment
        uses: actions/setup-rust@v1
      - name: Run cargo check
        run: cargo check
